name: alm
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - antlr4-python3-runtime==4.9.3
      - certifi==2022.6.15
      - cffi==1.15.1
      - charset-normalizer==2.1.0
      - click==8.1.3
      - cycler==0.12.1
      - cython==0.29.30
      - filelock==3.18.0
      - fonttools==4.57.0
      - future==0.18.2
      - gitdb==4.0.9
      - gitpython==3.1.27
      - glfw==2.5.3
      - gym==0.17.2
      - hydra-core==1.2.0
      - idna==3.3
      - imageio==2.19.3
      - importlib-resources==5.8.0
      - jinja2==3.1.6
      - joblib==1.1.0
      - kiwisolver==1.4.8
      - lockfile==0.12.2
      - markupsafe==3.0.2
      - matplotlib==3.5.3
      - mpmath==1.3.0
      - numpy==1.23.1
      - omegaconf==2.2.2
      - packaging==21.3
      - pathtools==0.1.2
      - pillow==9.2.0
      - protobuf==3.20.1
      - psutil==5.9.1
      - pycparser==2.21
      - pyglet==1.5.0
      - pyparsing==3.0.9
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0
      - requests==2.28.1
      - scikit-learn==1.1.1
      - scipy==1.8.1
      - sentry-sdk==1.6.0
      - setproctitle==1.2.3
      - shortuuid==1.0.9
      - six==1.16.0
      - smmap==5.0.0
      - sympy==1.13.1
      - threadpoolctl==3.1.0
      - torch==2.6.0
      - typing-extensions==4.12.2
      - urllib3==1.26.10
      - wandb==0.12.21
      - zipp==3.8.0