name: rl_perceptual
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.3
  - matplotlib=3.5.2
  - numpy=1.23.4
  - pytorch=1.13.0
  - torchvision=0.14.0
  - cudatoolkit=11.6
  - pip:
    - tqdm==4.64.1