wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1747065687
    t:
      1:
      - 1
      - 50
      - 55
      3:
      - 16
      4: 3.10.4
      5: 0.12.21
      8:
      - 8
agent:
  desc: null
  value: alm
batch_size:
  desc: null
  value: 512
benchmark:
  desc: null
  value: gym
device:
  desc: null
  value: cuda
env_buffer_size:
  desc: null
  value: 100000
eval_bias:
  desc: null
  value: false
eval_bias_interval:
  desc: null
  value: 500
eval_episode_interval:
  desc: null
  value: 5000
expl_duration:
  desc: null
  value: 100000
expl_end:
  desc: null
  value: 0.1
expl_start:
  desc: null
  value: 1.0
explore_steps:
  desc: null
  value: 5000
gamma:
  desc: null
  value: 0.99
hidden_dims:
  desc: null
  value: 512
id:
  desc: null
  value: Humanoid-v2
lambda_cost:
  desc: null
  value: 0.1
latent_dims:
  desc: null
  value: 50
log_interval:
  desc: null
  value: 500
lr:
  desc: null
  value: '{''model'': 0.0001, ''reward'': 0.0001, ''critic'': 0.0001, ''actor'': 0.0001}'
max_episode_steps:
  desc: null
  value: 1000
max_grad_norm:
  desc: null
  value: 100.0
model_hidden_dims:
  desc: null
  value: 1024
num_eval_episodes:
  desc: null
  value: 5
num_train_steps:
  desc: null
  value: 500000
save_snapshot:
  desc: null
  value: false
save_snapshot_interval:
  desc: null
  value: 50000
seed:
  desc: null
  value: 1
seq_len:
  desc: null
  value: 3
stddev_clip:
  desc: null
  value: 0.3
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
wandb_log:
  desc: null
  value: true
wandb_run_name:
  desc: null
  value: ALM
